# Generated by Django 5.0.6 on 2024-06-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
